import { createAsyncThunk, createSlice } from "@reduxjs/toolkit";
import { fetchQuote } from "./quoteAPI";

const initialState = {
	display: true,
	quote: {
		author: "Quazaq People",
		quote:
			"Yo Orystar Sheshen Am Qotaqtar Sap Sary Qotaq Sheshen Am Qaldyragan",
	},
};

// The function below is called a thunk and allows us to perform async logic. It
// can be dispatched like a regular action: `dispatch(incrementAsync(10))`. This
// will call the thunk with the `dispatch` function as the first argument. Async
// code can then be executed and other actions can be dispatched. Thunks are
// typically used to make async requests.
export const getNewQuote = createAsyncThunk(
	"randomQuotes/fetchQuote",
	async () => {
		try {
			const response = await fetchQuote();
			return response;
		} catch (error) {
			console.error(error);
		}
	}
);

export const randomQuoteSlice = createSlice({
	name: "randomQuote",
	initialState,
	reducers: {
		showQuotes: (state) => {
			state.display = true;
		},
		hideQuotes: (state) => {
			state.display = false;
		},
		// // Use the PayloadAction type to declare the contents of `action.payload`
		// incrementByAmount: (state, action) => {
		// 	state.value += action.payload;
		// },
	},
	// The `extraReducers` field lets the slice handle actions defined elsewhere,
	// including actions generated by createAsyncThunk or in other slices.
	extraReducers: (builder) => {
		builder
			.addCase(getNewQuote.pending, (state) => {})
			.addCase(getNewQuote.fulfilled, (state, action) => {
				state.quote = action.payload;
			});
	},
});

export const { showQuotes, hideQuotes } = randomQuoteSlice.actions;

// // The function below is called a selector and allows us to select a value from
// // the state. Selectors can also be defined inline where they're used instead of
// // in the slice file. For example: `useSelector((state: RootState) => state.counter.value)`
// export const selectCount = (state) => state.counter.value;

// // We can also write thunks by hand, which may contain both sync and async logic.
// // Here's an example of conditionally dispatching actions based on current state.
// export const incrementIfOdd = (amount) => (dispatch, getState) => {
// 	const currentValue = selectCount(getState());
// 	if (currentValue % 2 === 1) {
// 		dispatch(incrementByAmount(amount));
// 	}
// };

export default randomQuoteSlice.reducer;
